import java.awt.Color;
import java.util.Random;

public class TurtleLab
{
    public static void main(String args[])
    {
        World turtleWorld = new World();
        Turtle turtle = new Turtle(turtleWorld);
        Turtle rupert = new Turtle(turtleWorld);
        turtle.setName("Admiral Mimu");
        rupert.setName("Sir Rupert Robbington");
        turtle.setShellColor(Color.YELLOW);
        turtle.setBodyColor(Color.GREEN);
        turtle.setPenWidth(5);
        turtle.setPenColor(Color.BLUE);
        turtle.penDown();
        turtle.forward(50);
        turtle.penUp();
        turtle.turn(90);
        turtle.forward(100);
        turtle.turn(90);
        turtle.penDown();
        turtle.forward(50);
        turtle.penUp();
        turtle.setPenWidth(10);
        turtle.setPenColor(Color.GREEN);
        turtle.turn(25);
        turtle.forward(35);
        turtle.turn(20);
        turtle.penDown();
        turtle.forward(30);
        turtle.turn(45);
        turtle.forward(30);
        turtle.turn(45);
        turtle.forward(30);
        turtle.penUp();
        rupert.penUp();
        rupert.turn(-90);
        rupert.forward(100);
        rupert.setShellColor(Color.ORANGE);
        rupert.setBodyColor(Color.GREEN);
        turtle.forward(250);
        turtle.turn(-45);
        turtle.setPenColor(Color.RED);
        rupert.setPenColor(Color.CYAN);
        turtle.setPenWidth(8);
        rupert.setPenWidth(8);
        turtle.turn(-90);
        rupert.turn(90);
        turtle.penDown();
        turtle.forward(145);
        rupert.penDown();
        rupert.forward(145);
        turtle.turn(-90);
        rupert.turn(-90);
        turtle.forward(62);
        rupert.forward(62);
        turtle.turn(135);
        rupert.turn(-45);
        turtle.forward(200);
        rupert.forward(200);
        turtle.turn(135);
        rupert.turn(-45);
        turtle.forward(145);
        rupert.forward(145);
        rupert.turn(-90);
        turtle.turn(-90);
        turtle.forward(62);
        rupert.forward(62);
        turtle.penUp();
        turtle.turn(180);
        turtle.forward(62);
        turtle.turn(90);
        turtle.forward(145);
        turtle.turn(-135);
        turtle.forward(200);
        turtle.turn(45);
        turtle.forward(5);
        rupert.forward(5);
        turtle.turn(-90);
        rupert.turn(-90);
        turtle.forward(5);
        turtle.forward(5);
        turtle.setPenColor(Color.MAGENTA);
        rupert.setPenColor(Color.PINK);
        turtle.penDown();
        turtle.forward(145);
        rupert.penDown();
        rupert.forward(145);
        turtle.turn(-90);
        rupert.turn(-90);
        turtle.forward(62);
        rupert.forward(62);
        turtle.turn(135);
        rupert.turn(-45);
        turtle.forward(200);
        rupert.forward(200);
        turtle.turn(135);
        rupert.turn(-45);
        turtle.forward(145);
        rupert.forward(145);
        rupert.turn(-90);
        turtle.turn(-90);
        turtle.forward(62);
        rupert.penUp();
        rupert.forward(62);
        turtle.penUp();
        turtle.turn(180);
        turtle.forward(62);
        turtle.turn(90);
        turtle.forward(145);
        turtle.turn(-135);
        turtle.forward(200);
        turtle.turn(45);
        turtle.penUp();
        turtle.turn(180);
        turtle.forward(300);
        rupert.forward(575);
        rupert.turn(-90);
        rupert.forward(500);
        turtle.penDown();
        turtle.setPenColor(Color.BLACK);
        Random forward1 = new Random();
        Random turn1 = new Random();
        Random forward2 = new Random();
        Random turn2 = new Random();
        int x = 0;
        while ( x != 50 ) {
            turtle.setPenWidth(10);
            turtle.penDown();
            turtle.setPenColor(Color.BLUE);
            turtle.forward(70);
            turtle.turn(135);
            turtle.setPenColor(Color.ORANGE);
            turtle.forward(120);
            turtle.turn(155);
            turtle.setPenColor(Color.GREEN);
            turtle.forward(140);
            turtle.turn(145);
            turtle.setPenColor(Color.RED);
            turtle.forward(140);
            turtle.setPenColor(Color.BLACK);
            turtle.turn(154);
            turtle.forward(115);
            turtle.penUp();
            int forValue1 = forward1.nextInt( 50 );
            int turnValue1 = turn1.nextInt( 180 );
            int forValue2 = forward2.nextInt( 50 );
            int turnValue2 = turn2.nextInt( 180 );
            turtle.turnToFace(rupert);
            turtle.forward(forValue1);
            rupert.penUp();
            rupert.turn(turnValue1);
            rupert.forward(forValue2);
            rupert.turn(turnValue2);
            x += 1;
        }
    }
}
